FROM alpine:3.12

RUN apk update && apk upgrade

# устанавливаю NGINX WGET SUPERVISOR
RUN apk add nginx wget supervisor openssl openssh
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

# устанавливаю необходимые пакеты для  NGINX
RUN apk add php7 php7-fpm php7-mbstring

# настройка nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.config /etc/nginx/conf.d/default.conf
RUN mkdir -p /run/nginx
COPY ./index.html /www/index.html
COPY ./style.css /www/style.css

# настройка Supervisor
COPY ./supervisord.conf /etc/supervisord.conf
COPY ./telegraf.conf /etc/telegraf/

# Устанавливаем ssh и пользователя
RUN ssh-keygen -A && adduser -D user && echo "user:pass" | chpasswd

# Устанавливаем сертификаты
RUN openssl req -x509 -nodes -days 365 -subj "/C=RU/ST=Russia/L=Kazan/O=school/OU=21school/CN=drogue" -newkey rsa:2048 -keyout /etc/ssl/nginx-selfsigned.key -out /etc/ssl/nginx-selfsigned.crt;

EXPOSE 80 443 22

CMD /bin/sh -c "/usr/bin/supervisord -c /etc/supervisord.conf"
