FROM alpine:3.12

RUN apk update
RUN apk upgrade
RUN apk add sudo vim mysql mysql-client supervisor \
    openrc mariadb mariadb-common mariadb-client
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

RUN mkdir -p /run/mysqld/
COPY ./supervisord.conf /etc/supervisord.conf
COPY ./wordpress.sql /
COPY ./my.cnf /etc/
COPY ./startup.sh ./
COPY ./telegraf.conf /etc/telegraf/
RUN sudo chmod -R 755 /var/lib/mysql/

# Открытие волюма
VOLUME ["/var/lib/mysql"]

# Открытие портов
EXPOSE 3306

# Запуск
CMD ./startup.sh
