FROM alpine:3.12

RUN apk update && apk upgrade

RUN apk add supervisor influxdb
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

COPY ./supervisord.conf /etc/supervisord.conf
COPY ./telegraf.conf /etc/telegraf/
COPY ./start.sh ./
RUN chmod +x start.sh

VOLUME ["var/lib/influxdb"]

EXPOSE 8086

CMD ./start.sh
