FROM alpine:3.12

RUN apk update && apk upgrade

# устанавливаю NGINX WGET SUPERVISOR
RUN apk add nginx wget supervisor
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

# устанавливаю необходимые пакеты для  NGINX
RUN apk add php7 php7-fpm php7-mbstring

# устанавливаю необходимые пакеты для Wordpress
RUN apk add lighttpd php7-common php7-session php7-iconv php7-json \
	php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi \
	php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix \
	php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom

# создаю папку
RUN mkdir -p /usr/share/webapps/

# скачиваю и устанавливаю туда WORDPRESS
RUN cd /usr/share/webapps/ && wget http://wordpress.org/latest.tar.gz && tar -xzvf latest.tar.gz && rm latest.tar.gz

# настройка Wordpress
RUN chown -R lighttpd /usr/share/webapps/
RUN ln -s /usr/share/webapps/wordpress/ /var/www/localhost/htdocs/wordpress
COPY ./wp-config.php /usr/share/webapps/wordpress/
RUN mkdir -p /var/run/php

# настройка nginx
COPY ./nginx.config /etc/nginx/conf.d/default.conf
RUN mkdir -p /run/nginx

# настройка Supervisor
COPY ./supervisord.conf /etc/supervisord.conf

COPY ./telegraf.conf /etc/telegraf/

EXPOSE 5050

CMD /bin/sh -c "/usr/bin/supervisord -c /etc/supervisord.conf"
