FROM alpine:3.12

RUN apk update && apk upgrade

# устанавливаю NGINX WGET SUPERVISOR
RUN apk add nginx wget supervisor
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/

# устанавливаю необходимые пакеты для  NGINX
RUN apk add php7 php7-fpm php7-mbstring

# устанавливаю необходимые пакеты для phpmyadmin
RUN apk add lighttpd php7-common php7-session php7-iconv php7-json \
	php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi \
	php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix \
	php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom

# скачиваю и устанавливаю туда phpmyadmin
RUN wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz
RUN tar -zxvf phpMyAdmin-5.0.2-all-languages.tar.gz
RUN rm -rf phpMyAdmin-5.0.2-all-languages.tar.gz
RUN mkdir -p /www
RUN mv phpMyAdmin-5.0.2-all-languages /www/phpmyadmin


# настройка phpmyadmin
COPY ./config.inc.php /www/phpmyadmin/
RUN mkdir -p /var/run/php
COPY ./telegraf.conf /etc/telegraf/

# настройка nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.config /etc/nginx/conf.d/default.conf
RUN mkdir -p /run/nginx

# настройка Supervisor

COPY ./supervisord.conf /etc/supervisord.conf

EXPOSE 5000

CMD /bin/sh -c "/usr/bin/supervisord -c /etc/supervisord.conf"
